<a href="https://colab.research.google.com/github/ardiwaaaa/Processing_Data/blob/main/Processing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks.
Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.

In [3]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Italy' 30.0 nan]
 ['Portugal' nan 70000.0]
 ['France' 41.0 65000.0]
 ['Spain' 25.0 85000.0]
 ['Germany' 55.0 nan]
 ['Italy' nan 75000.0]
 ['Portugal' 30.0 60000.0]
 ['France' 38.0 nan]
 ['Spain' 37.0 55000.0]
 ['Germany' 35.0 80000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No'
 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform (x[:, 1:3])

In [7]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 66500.0]
 ['France' 35.0 58000.0]
 ['Spain' 37.64705882352941 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Italy' 30.0 66500.0]
 ['Portugal' 37.64705882352941 70000.0]
 ['France' 41.0 65000.0]
 ['Spain' 25.0 85000.0]
 ['Germany' 55.0 66500.0]
 ['Italy' 37.64705882352941 75000.0]
 ['Portugal' 30.0 60000.0]
 ['France' 38.0 66500.0]
 ['Spain' 37.0 55000.0]
 ['Germany' 35.0 80000.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [11]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 66500.0]
 [1.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 1.0 37.64705882352941 52000.0]
 [1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 30.0 66500.0]
 [0.0 0.0 0.0 1.0 0.0 37.64705882352941 70000.0]
 [1.0 0.0 0.0 0.0 0.0 41.0 65000.0]
 [0.0 0.0 0.0 0.0 1.0 25.0 85000.0]
 [0.0 1.0 0.0 0.0 0.0 55.0 66500.0]
 [0.0 0.0 1.0 0.0 0.0 37.64705882352941 75000.0]
 [0.0 0.0 0.0 1.0 0.0 30.0 60000.0]
 [1.0 0.0 0.0 0.0 0.0 38.0 66500.0]
 [0.0 0.0 0.0 0.0 1.0 37.0 55000.0]
 [0.0 1.0 0.0 0.0 0.0 35.0 80000.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 0 1]


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
random_state=1)

In [17]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 0.0 55.0 66500.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 66500.0]
 [1.0 0.0 0.0 0.0 0.0 38.0 66500.0]
 [1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 1.0 25.0 85000.0]
 [1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 35.0 80000.0]
 [0.0 0.0 0.0 0.0 1.0 37.0 55000.0]
 [1.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 37.64705882352941 75000.0]
 [0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 41.0 65000.0]
 [0.0 0.0 0.0 1.0 0.0 37.64705882352941 70000.0]
 [1.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [18]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 30.0 60000.0]
 [0.0 0.0 0.0 0.0 1.0 37.64705882352941 52000.0]
 [0.0 0.0 1.0 0.0 0.0 30.0 66500.0]]


In [19]:
print(y_train)

[0 0 1 0 1 1 1 0 1 0 1 1 0 0 0 1]


In [20]:
print(y_test)

[0 1 0 1]


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [22]:
print(x_train)

[[0.0 1.0 0.0 -0.2581988897471611 -0.48038446141526137
  -1.1131042848876458 -1.3616503082968652]
 [0.0 1.0 0.0 -0.2581988897471611 -0.48038446141526137 2.1298730661132086
  -0.15931008022016305]
 [0.0 1.0 0.0 -0.2581988897471611 -0.48038446141526137
  0.18408665551269587 -0.15931008022016305]
 [1.0 0.0 0.0 -0.2581988897471611 -0.48038446141526137
  -0.07535153256737247 -0.15931008022016305]
 [1.0 0.0 0.0 -0.2581988897471611 -0.48038446141526137 1.2218394078329693
  1.0430301478565391]
 [0.0 0.0 0.0 -0.2581988897471611 2.0816659994661326 -1.5022615670077484
  -1.9387736177736823]
 [0.0 0.0 0.0 -0.2581988897471611 2.0816659994661326 -1.7616997550878166
  1.6201534573333563]
 [1.0 0.0 0.0 -0.2581988897471611 -0.48038446141526137 0.7029630316728326
  0.36971962013358595]
 [0.0 1.0 0.0 -0.2581988897471611 -0.48038446141526137
  -0.46450881468747496 1.1392173661026754]
 [0.0 0.0 0.0 -0.2581988897471611 2.0816659994661326 -0.20507062660740663
  -1.265463090050729]
 [1.0 0.0 0.0 -0.2581988897

In [23]:
print(x_test)

[[0.0 0.0 0.0 -0.2581988897471611 2.0816659994661326 -0.07535153256737247
  -0.688339780573912]
 [0.0 0.0 0.0 3.8729833462074166 -0.48038446141526137 -1.1131042848876458
  -0.7845269988200482]
 [0.0 0.0 0.0 -0.2581988897471611 2.0816659994661326 -0.12113474222856083
  -1.5540247447891375]
 [0.0 0.0 1.0 -0.2581988897471611 -0.48038446141526137
  -1.1131042848876458 -0.15931008022016305]]
